### ISSUE TITLE
Syntax for targets

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-Parser#10]
Currently, target syntax has something like this:

```
(targetname)=

# Some header
```

What do folks think about this?

Another idea that might be worth exploring is to look into using an in-line syntax for targets. If I recall, they only work for headers anyway, so what if we defined targets with something like:

```
# My header name ={mytargetname}
```

Though that might break down if we ever supported things like extra attributes syntax

**Comment by chrisjsewell** [comment]
For more context, `targets` are handled by `docutils.transforms.references.PropagateTargets`, which
propagate empty internal targets to the next element.

```xml
<document source="">
    <target ids="target" names="target">
    <section ids="header-1" names="header\ 1">
```

```xml
<document source="">
    <target refid="target">
    <section ids="header target" names="header target">
```

You can actually use it for more than headers, although that;s there main use.

The issue with doing `# My header name ={mytargetname}` is that you'll end up with something like:

```xml
<header>
    <raw text>
        My header name
   <target>
        mytargetname
```

Then, when you convert to the docutils tree, you have to work out how to reposition the target up above the header.

**Comment by choldgraf** [comment]
Makes sense to me - I didn't realize it was in-built to Sphinx to grab the next thing, in that case I agree we should keep it before the headers
