### ISSUE TITLE
[Install] Incompatible with current awscli install 

### ISSUE THREAD

**Issue by mmcky** [ExecutableBookProject/MyST-Parser#100]
**Describe the bug**

Running the install for this package conflicts with a current install of `awscli` due to requirement for `docutils>=0.16`

```bash
ERROR: botocore 1.15.12 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
ERROR: awscli 1.18.12 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
Installing collected packages: docutils, myst-parser
  Found existing installation: docutils 0.14
ERROR: Cannot uninstall 'docutils'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

@chrisjsewell indicated we only required `docutils>=0.15` -- should this be specified in `setup.py`? 

I tend to think we should develop to the latest version though so perhaps `environments` are better in this case.

**Comment by chrisjsewell** [comment]
Yeh obviously all the development/testing has been done in docutils>=0.16, so it couldn’t be ‘guaranteed’ that 0.15 wouldn’t introduce a bug. But, looking at the [release notes](https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-15-2019-07-20) it doesn’t look like there would be any breaking changes.

**Comment by mmcky** [comment]
thanks @chrisjsewell -- understood. Will just work in an environment.

**Comment by chrisjsewell** [comment]
That’s always the best way 😉
