### ISSUE TITLE
Parsing a single line without a newline always results in paragraph

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-Parser#101]
I ran into a weird bug and I'm not sure if it's a bug or not :-)

If I run the MyST parser on a single line with no newline, then the result is always a paragraph, even if the line is a heading. E.g.:

```
from myst_parser.block_tokens import tokenize
tokenize("# Header\n".splitlines(keepends=True))
```

results in a `Heading` token, but:

```
from myst_parser.block_tokens import tokenize
tokenize("# Header".splitlines(keepends=True))
```

Results in a `Paragraph` token

This is semi-common in notebooks, if a user puts a single header line in a markdown cell.

**Comment by chrisjsewell** [comment]
Yeh the ‘Document’ which is the normal entry point for parsing, adds new lines: https://github.com/ExecutableBookProject/MyST-Parser/blob/9d27deeda9bd3418bfabcf064f1a9b4a066f6912/myst_parser/block_tokens.py#L89

**Comment by chrisjsewell** [comment]
I guess it’s  even generally assumed that tokenize will be called through this.

**Comment by choldgraf** [comment]
good to know - in this case we are explicitly not using `Document`, so I'll just add the newlines manually if the string doesn't end with one

**Comment by choldgraf** [comment]
Shall I close this as expected behavior?

**Comment by chrisjsewell** [comment]
Nah not just yet (see comment in mentioned issue)
