### ISSUE TITLE
No support for in-line markup that spans multiple lines in text file

### ISSUE THREAD

**Issue by mmcky** [ExecutableBookProject/MyST-Parser#124]
**Describe the bug**

The following text snippet will work in many `sphinx` projects in addition to `jupyter notebook` markdown cells. 

```
Consider again the linear model $x_{t+1} = a x_t + b$ with $a
\not=1$.
```

however `myst-parser==0.8.0a3` will render the first inline math and turn the second into literals. The output looks like:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/8263752/78098199-0b953e00-742a-11ea-87db-0a40ab2faf0f.png">

**Expected behavior**

I think we should support multi-line inline items given their support in jupyter notebooks

<img width="731" alt="image" src="https://user-images.githubusercontent.com/8263752/78098766-afcbb480-742b-11ea-9f61-0b6a0c9b741b.png">

**Environment (please complete the following information):**
- myst-parser==0.8.0a3

**Additional context**

**Comment by chrisjsewell** [comment]
Fixed in `myst-parser==0.8.0a4`, please give that a go and report back!
