### ISSUE TITLE
Make CircleCI fail on sphinx warnings 

### ISSUE THREAD

**Issue by chrisjsewell** [ExecutableBookProject/MyST-Parser#40]
With #38 (thanks @rossbar) the documentation build is closer to being able to run with no warnings.
At this point @choldgraf we can add the `sphinx-build` [nitpick options](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#options) `-nW` here: https://github.com/ExecutableBookProject/myst_parser/blob/8c7c7a7cd856836e73d0d9de7e6827ac4da6c29d/docs/Makefile#L20

For local debugging, we can also add a `make debug` option to the Makefile, as I do [here](https://github.com/chrisjsewell/ipypublish/blob/develop/docs/Makefile).

**Comment by choldgraf** [comment]
I think it's a good idea 👍
