### ISSUE TITLE
Replicate directive parsing behaviour of RST parser(?)

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-Parser#55]
I was looking into using this sphinx extension to handle the MyST vs. rST comparison:

https://github.com/djungelorm/sphinx-tabs

It uses a top-level directive `.. tabs::` that should take no arguments. However, I found that when I use this directive in MyST with:

````
```{tabs}
```
````

I am getting an error that arguments are passed to the `tabs` directive. The error shows because the directive says it takes *zero* arguments.

I am wondering if we are passing an empty argument, or something like this?

Here's a PR that shows off this behavior: https://github.com/ExecutableBookProject/myst_parser/pull/60

**Comment by chrisjsewell** [comment]
Yeh no problem, I’ll look into it

**Comment by choldgraf** [comment]
I have been trying to figure out what's going on, and the only difference I can find between the MyST and the docutils statemachine seems to be in the `parse_directive_arguments` method:

```
    def parse_directive_arguments(directive, arg_text):
        print("md", type(arg_text))
```

If I print a `type` on each iteration like so:

```
    def parse_directive_arguments(directive, arg_text):
        print("md", type(arg_text))
```

Then I get these outputs:

* docutils function:  `<class 'docutils.statemachine.StringList'>`
* MyST function: `<class 'str'>`

No idea if that has something to do with this error, but I'm just trying to figure out where behavior is different between the two packages

**Comment by chrisjsewell** [comment]
Don't worry I've already taken care of it in https://github.com/ExecutableBookProject/myst_parser/tree/restructure-testing, PR to come soon

**Comment by chrisjsewell** [comment]
It was because the `CodeFence` regex was including the line break character as part of the argument string.

**Comment by chrisjsewell** [comment]
This PR will also handle the directive option indentation #54

**Comment by choldgraf** [comment]
Note that this doesn't seem to be fixed. Now when I run the same code (after a rebase), I get a warning instead of a break, but it's the same warning (1 argument passed while 0 expected). Gonna re-open this so we don't lose track of it, in case there is an underlying issue that's causing this

**Comment by choldgraf** [comment]
Note - here is an example of code that causes this behavior: https://github.com/ExecutableBookProject/myst_parser/pull/60

**Comment by chrisjsewell** [comment]
To clarify this issue: the docutils parser [here](https://github.com/docutils-mirror/docutils/blob/e88c5fb08d5cdfa8b4ac1020dd6f7177778d5990/docutils/parsers/rst/states.py#L2118)
does not rigidly specify the structure of the directive block:

```restructuredtext
.. <name>:: <arguments>
    <option block>

   <body>
```

Instead, if no required/optional arguments are specified; the `<option block>` can start at `<arguments>` or, if no required/optional arguments are specified **and** no options are specified; the `<body>` block can start at `<arguments>`. Examples:

```restructuredtext
.. content:: :depth: 2
```

```restructuredtext
.. note:: This is body text
```
