### ISSUE TITLE
Inconsistencies between `readthedocs` and circleci docs

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-Parser#68]
There are some inconsistencies between RTD and Circle builds. For example:

* RTD: https://myst-parser.readthedocs.io/en/latest/using/syntax.html#nesting-directives
* CircleCI: https://125-240151150-gh.circle-artifacts.com/0/html/using/syntax.html#nesting-directives

In particular, **note blocks are classed differently**. The RTD docs class things as `admonition` while the CircleCI docs class things as `alert`

I think this is related to the pydata bootstrap theme re-classing (https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/blob/master/pandas_sphinx_theme/bootstrap_html_translator.py#L44). This is code that replaces common Sphinx classes with the respective bootstrap classes so that the CSS shows up.

For some reason, this replacement happens in CircleCI, but not in readthedocs...

**Comment by choldgraf** [comment]
also opened up https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/issues/94 to track this

**Comment by choldgraf** [comment]
ah this might be our problem: https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/issues/94#issuecomment-589401645

**Comment by choldgraf** [comment]
I believe that https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/pull/95 will fix our problem, let's find out once it's merged

**Comment by chrisjsewell** [comment]
> I believe that [pandas-dev/pydata-bootstrap-sphinx-theme#95](https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/pull/95) will fix our problem, let's find out once it's merged

Yep that did it 😄
