### ISSUE TITLE
Document how to use MyST as a python module

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-Parser#70]
Thus far our documentation has focused on the Sphinx parsing and authoring side, but we should also document how to import MyST, run it on markdown, understand the AST, etc.

**Comment by chrisjsewell** [comment]
We should also use `sphinx-apidoc` in the `conf.py` to auto generate the API documentation, similar to what I do in: https://github.com/chrisjsewell/ase-notebook/blob/fdf5abb403c17f544453c1afd9e9bdaae4826a6d/docs/source/conf.py#L285
