### ISSUE TITLE
Convert most of the README to links in the documentation

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-Parser#85]
What do people think about converting much of the README into links to places in the documentation? This could help us cut-back on duplicated content that may be hard to remember to update.

I think basic "install and usage" stuff is fine in the README, but other stuff like supported syntax would be better to have in a single canonical place.

Another option would be to use `include` statements in our documentation and pull from the README.

**Comment by chrisjsewell** [comment]
Yep agree. I don't fancy the `include` route, just seems to 'fiddly'

**Comment by chrisjsewell** [comment]
closed in #119
