### ISSUE TITLE
Bibtex bibliography directive renders unreferenced citation

### ISSUE THREAD

**Issue by mtiley** [ExecutableBookProject/MyST-Parser#95]
This happens when there are user errors in the `{cite}` roles in the document (specifically, reference to something not in the .bib)

**To Reproduce**
1. `{cite}` something that is not in reference.bib 
2. put in a `{bibliography}` 
3. observe that the bibliography contains references not cited in the document

**Edit**: Sorry, this is wrong. Another instance [here](https://github.com/ExecutableBookProject/myst-parser.example-project/issues/11) with different cause.

**Screenshots**
Here is a citation with no corresponding entry in references.bib
<img width="300" alt="refin" src="https://user-images.githubusercontent.com/56301568/75645789-6a389200-5c9b-11ea-8b55-fa4e72bc4027.PNG">
The `bibliography` outputs a *different* reference:
<img width="420" alt="refout" src="https://user-images.githubusercontent.com/56301568/75645793-6b69bf00-5c9b-11ea-8b11-d8cae47122c5.PNG">

(This doesn't happen with rST and seems to be introduced by myst_parser. The following is in a separate Sphinx project with only sphinxcontrib.bibtex as an extension.) See input:
<img width="350" alt="bib1" src="https://user-images.githubusercontent.com/56301568/75647097-fb116c80-5c9f-11ea-9c8e-9f904b06601d.PNG">

html output:
<img width="398" alt="bib2" src="https://user-images.githubusercontent.com/56301568/75647101-ff3d8a00-5c9f-11ea-93ae-386a23e86a71.PNG">

**Environment:**
 - myst-parser 0.2.0
 - sphinxcontrib.bibtex 1.0.0

**Comment by mmcky** [comment]
@mtiley is the incorrect reference resolving to the nearest reference in the `references.bib` file? It is an issue that the incorrect reference is getting adding rather than throwing an error that it cannot resolve the reference. This is likely a `sphinx` `translator` issue? @chrisjsewell is the `AST` correct for the `parser`?

**Comment by mtiley** [comment]
@mmcky I don't think so -- Yuna will be doing some more testing tomorrow.

This is the .bib file I was using (had to change to .txt to upload): [references.txt](https://github.com/ExecutableBookProject/MyST-Parser/files/4310558/references_githubfriendly.txt)

**Comment by mtiley** [comment]
Update: I have replicated the problem in a project (files [here](https://github.com/mtiley/Bibtex-issue-no-myst-parser-)) without `myst-parser` (only `sphinxcontrib.bibtex`) as an extension. Seems to be an issue with (or feature of) sphinxcontrib-bibtex and not introduced by myst-parser after all -- so I think this issue can be closed.

Discussion here https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/62 and here https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/52 

The problem appears to be fixed in rST by adding a `:filter: docname in docnames` option to the bibliography directive so that only citations in that particular document appear in the bibliography. I can't get this to work in MyST at the moment but will play around with it a bit more.

**Comment by chrisjsewell** [comment]
@mtiley ok I'll close this issue for now then, and if you do uncover a discrepancy, please open another issue and, if possible, a PR with a minimal working example; in a similar fashion to what I did in #97 (adding to https://github.com/ExecutableBookProject/MyST-Parser/tree/master/tests/test_sphinx)
